name: Link Checker

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@<sha>
        with:
          args: --verbose --no-progress **/*.md
